### ISSUE TITLE
PHP Fatal error:  Declaration of Bugsnag\PsrLogger\BugsnagLogger::log

### ISSUE THREAD

**Issue by Eugene-Melbourne** [bugsnag/bugsnag-laravel#491] opened 2022-05-25 03:54 UTC
### Describe the bug
after I upgreded to PHP 8  bugsnag is not working

PHP Fatal error:  Declaration of Bugsnag\PsrLogger\BugsnagLogger::log(mixed $level, Stringable|string $message, array $context = []): void must be compatible with PsrExt\Log\LoggerInterface::log($level, $message, array $context = []) in /var/www/default/vendor/bugsnag/bugsnag-psr-logger/src/BugsnagLogger.php on line 66

### Environment
* Bugsnag version: v2.24.0
* PHP version: 8.0
* Composer version: 2.3.5
* Laravel version: 8.83.13

**Comment by Eugene-Melbourne** [comment] 2022-05-26 00:31
It may have something to do with php8.0-psr
I have it installed 

https://linux-packages.com/ubuntu-jammy-jellyfish/package/php80-psr

**Comment by johnkiely1** [comment] 2022-05-26 08:44
Hi @Eugene-Melbourne, 

Did you make any changes to the Bugsnag configuration at the same time as upgrading to Php 8?  Would you mind sharing what your Bugsnag configuration currently looks like. Feel free to do that here or write in to us at support@bugsnag.com

**Comment by Eugene-Melbourne** [comment] 2022-05-29 23:21
I did not make any changes Bugsnag configuration. In my previous comment I mention the php8.0-psr. Bitbucket does not work with this php module.

**Comment by johnkiely1** [comment] 2022-06-09 09:06
Hi @Eugene-Melbourne,  thanks.  We are looking into this now, I'm going to go ahead and close this issue as it is essentially a duplicate of https://github.com/bugsnag/bugsnag-psr-logger/issues/54 and we can continue the discussion on that one.

**Closed by johnkiely1** 2022-06-09 09:06 UTC
Labels: awaiting feedback
