### ISSUE TITLE
Call to undefined method Bugsnag\BugsnagLaravel\MultiLogger::getMonolog()

### ISSUE THREAD

**Issue by wkolcz-UMHS** [bugsnag/bugsnag-laravel#233] opened 2017-05-17 14:43 UTC
I was using BugSnag with my Laravel 5.4 app and recently updating the app and now I get an error when I run composer update

Call to undefined method Bugsnag\BugsnagLaravel\MultiLogger::getMonolog() which, when inspected your vendor code, the function does not exist.

I am running;
"laravel/framework": "5.4.*",
"bugsnag/bugsnag": "^3.5",
 "bugsnag/bugsnag-laravel": "^2.4",

and have it registered in the AppServiceProvider as instructed in your setup:

public function register()
    {
        $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
        $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
    }

**Comment by wkolcz-UMHS** [comment] 2017-05-17 15:01
Oddly enough it wasn't Bugsnag as the only issue. There is another class trying to call \Log::getMonolog() that is failing since apparently Bugsnag takes over the logging.

interesting it was your web dashboard that lead me to discover that the issue with a conflict between another library and the Bugsnag library. Any ideas?

**Comment by GrahamCampbell** [comment] 2017-05-17 17:59
Thanks for the report. This is ultimately a duplicate of #231, since the fix will be the same. Thank you very much for reporting though. I'll close this up so we only have one issue. :)

**Closed by GrahamCampbell** 2017-05-17 17:59 UTC

**Comment by wkolcz-UMHS** [comment] 2017-05-17 18:14
Thanks @GrahamCampbell!
