### ISSUE TITLE
Not reporting failed job on Laravel vapor

### ISSUE THREAD

**Issue by usrNotFound** [bugsnag/bugsnag-laravel#427] opened 2021-01-04 05:07 UTC
### Describe the bug
Laravel vapor project won't report an error on bugsnag for failed queued job.

### Steps to reproduce
1. configure logging
``` "vapor" => [
            "driver" => "stack",
            "channels" => ["bugsnag", "stderr"],
            "ignore_exceptions" => false,
        ],

        "bugsnag" => [
            "driver" => "bugsnag",
        ],
```

2. Add BugsnagServiceProvider to app.php
4. set`QUEUE_CONNECTION` to `'redis', 'sqs' anything other than 'sync'
5. Create a job and implement `ShouldQueue` with `throw new Exception`
6. Run project and dispatch the job.

### Environment
* Bugsnag version: 2.21.0
* PHP version: 7.4
* Composer version: 2
* Laravel version: 6.20
* Lumen version (if any):

**Comment by mattdyoung** [comment] 2021-01-06 12:39
We don't yet provide support for using Bugsnag in AWS Lambda environments such as Laravel Vapor.

We suspect the issue is likely to be that the process is being terminated before the error report is delivered to Bugsnag, as the report is being sent asynchronously.

In general for serverless environments, setting the batch sending option to `false` may help as this will send the report when the error occurs:
https://docs.bugsnag.com/platforms/php/laravel/configuration-options/#batch-sending

This may not resolve the issue you're seeing for queued jobs though.

We'll be sure to update this issue if we release full support in the future.

**Comment by fideloper** [comment] 2021-06-18 19:40
Both issues are true I believe.

I have the following `config/logging.php` (some stuff omitted):

```php
<?php

return [
    'default' => env('LOG_CHANNEL', 'stack-'.env('APP_ENV')),

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'bugsnag'],
            'ignore_exceptions' => false,
        ],

        'stack-production' => [
            'driver' => 'stack',
            'channels' => ['single', 'stderr', 'bugsnag'],
            'ignore_exceptions' => false,
        ],

        'stack-staging' => [
            'driver' => 'stack',
            'channels' => ['single', 'stderr', 'bugsnag'],
            'ignore_exceptions' => false,
        ],
    ],
];
```

Web requests appear to send errors to Bugsnag  just fine, but queue jobs do not.

In the past, this has been caused when `__destruct()` calls are never fired in PHP, which happens when running `tinker` sessions as well.

Setting batch settings to `false` can indeed help this:

```
BUGSNAG_BATCH_SENDING=false
```

**Comment by GrahamCampbell** [comment] 2021-06-18 19:44
You probs don't wanna write to single on vapor. It'll just fill your tmp directory. If you write a lot, you'll start getting 502s from api gateway.

**Comment by fideloper** [comment] 2021-06-18 19:45
I was wondering about that - I've been assuming each lambda and its tmp drive is killed between each request. I guess that's not the case?

**Comment by GrahamCampbell** [comment] 2021-06-18 19:48
No. They keep it around. This is how warm starts are implemented. Each lambda is not gonna share the same tmp directory, but the filesystem from one that has shutdown already can get reused for another lambda about to boot. :)

**Comment by gareththackeray** [comment] 2023-01-17 13:29
This is now fixed in [v2.25.1](https://github.com/bugsnag/bugsnag-laravel/releases/tag/v2.25.1).  Any problems please let us know.

**Closed by gareththackeray** 2023-01-17 13:29 UTC
Labels: feature request, backlog

**Comment by aligajani** [comment] 2024-05-09 03:39
@gareththackeray  You just linked `localhost`

**Comment by gareththackeray** [comment] 2024-05-09 07:02
> @gareththackeray  You just linked `localhost`

Oops thanks. Fixed
