### ISSUE TITLE
Sending asynchronous requests [feature request]

### ISSUE THREAD

**Issue by 120dev** [bugsnag/bugsnag-laravel#318] opened 2018-10-01 04:48 UTC
Hello, is it possible to send the requests in asynchronous ? this would avoid blocking the user-side process.

thank you very much

**Comment by GrahamCampbell** [comment] 2018-10-01 07:42
Bugsnag won't block the user already by default, since it sends error reports after the response has been served to the user.:)

**Comment by 120dev** [comment] 2018-10-01 11:29
thanks for the return, however if a webhook is configured, the user feedback is done once the webhook is deployed (notifi slack in this case)

Laravel 5.7

**Comment by 120dev** [comment] 2018-10-24 03:42
Hi @Cawllec 

I configured in (parameter -> integration) a webhook to Slack.

And when I do a `Log :: error ('hello world !!');` the backend (it's on an API), only responds when the webhook is gone to slack and slack sent back to the channel

here is an example with bugsnag and without bugsnag

![mbp120 2018-10-24 a 14 40 59](https://user-images.githubusercontent.com/4286701/47404917-f4fda880-d79a-11e8-9035-2a8fb8a3c2df.jpg)


`bugsnag/bugsnag-laravel: "^2.0",`
`laravel/passport: "~7.0",`

**Comment by ankurk91** [comment] 2018-11-04 18:02
@120dev
Are you referring to Async request feature in Guzzle?
http://docs.guzzlephp.org/en/stable/quickstart.html#async-requests

**Comment by Cawllec** [comment] 2019-01-17 15:56
Can I ask how you are testing this @120dev?  Through some quick testing I'm seeing very little difference in response times between Bugsnag being activated or not, but performance is important and this is something we'd like to reproduce if we can.

**Comment by Cawllec** [comment] 2019-01-29 10:13
I'm closing this thread for now, however if you have any issues or reproduction cases please get in contact.

**Closed by Cawllec** 2019-01-29 10:13 UTC
Labels: awaiting user feedback, feedback

**Comment by 120dev** [comment] 2019-02-02 10:48
Hello,

sorry for the delay

I still think that the whole process is synchrone, you should not have the same feeling because you must have low latency on the internet, I test from New Caledonia.
I notice especially this latency when I do tests from my computer, when it is on the servers we do not notice this latency because the connections are fast. That's what makes me think that it's not asynchronous.

To reproduce the test it is not complicated

`Bugsnag::notifyException($e);`

on bugsnag is configured a webhook to slack.

With Bugsnag & webhook to slack
![mbp120 2019-02-02 a 21 45 05](https://user-images.githubusercontent.com/4286701/52163267-d7de5b80-2733-11e9-8ef5-8f11242a03ac.jpg)

Without :

![mbp120 2019-02-02 a 21 46 17](https://user-images.githubusercontent.com/4286701/52163284-ffcdbf00-2733-11e9-8025-167692be8538.jpg)

```
    "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-dompdf": "^0.8.3",
        "bugsnag/bugsnag-laravel": "^2.0",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.7.*",
        "laravel/passport": "~7.0",
        "laravel/tinker": "^1.0",
        "owen-it/laravel-auditing": "^8.0",
        "predis/predis": "^1.1",
        "spatie/laravel-fractal": "^5.4"
    },
```

**Comment by GrahamCampbell** [comment] 2019-02-03 14:05
I think all the bytes of the request should have been sent within the first 251ms in the "with" case however. Is you load balancer keeping the request from being closed?
