### ISSUE TITLE
Fatal error: Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by babinicz01** [bugsnag/bugsnag-laravel#307] opened 2018-06-27 13:56 UTC
I try to upload my backup files to local flywheel wordpress site. In case of big type files such as "uploads" (~4GB size) and "others" (~3GB size) appears information such as that one:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 386216136 bytes) in /app/public/wp-admin/includes/file.php on line 
> 1190

All picture: [https://drive.google.com/file/d/1Ww-pza_M6gkHR7Kq8U3NLRNE2N23OvkX/view?usp=sharing](https://drive.google.com/file/d/1Ww-pza_M6gkHR7Kq8U3NLRNE2N23OvkX/view?usp=sharing)

**Virtual server info:**
Web Serwer: nginx
PHP Version: 7.0.3
MySQL Version: 5.5.55
WordPress Version: 4.9.6

**Two questions:**
1. What should I do to solve this problem?
2. All of it I do to check if my site will be working on 7.0 PHP version. Can I verify this if I only test my site basing on it what I've manages to upload?

I'll be greatful for your help :)

**Comment by kattrali** [comment] 2018-06-27 18:55
Unfortunately, this doesn't seem to be an issue with the Bugsnag Laravel integration. Perhaps this was intended for a different repository? Closing for now but feel free to reopen if this is a misunderstanding.

**Closed by kattrali** 2018-06-27 18:55 UTC
