### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Class bugsnag.logger does not exist'

### ISSUE THREAD

**Issue by rickytribbia** [bugsnag/bugsnag-laravel#181] opened 2016-08-17 13:38 UTC
My `composer.json` contains: 

```
"bugsnag/bugsnag-laravel": "^2.0"
```

Into my `config/app.php` I have: 

```
'providers' => [
    ...
    Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,
    ...
]
```

and:

```
'aliases' => [
    ...
    'Bugsnag' => Bugsnag\BugsnagLaravel\Facades\Bugsnag::class,
    ...
]
```

My `AppServiceProvider.php` contains:

```
use Illuminate\Contracts\Logging\Log;
use Psr\Log\LoggerInterface;

    ...
    public function register()
    {
        $this->app->alias('bugsnag.logger', Log::class);
        $this->app->alias('bugsnag.logger', LoggerInterface::class);
    }
```

In my `.env` file I set `BUGSNAG_API_KEY`. 

And I continously get the error (running `php artisan serve` or `composer update`, etc):

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag.logger does not exist' in {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('bugsnag.logger')
#1 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('bugsnag.logger', Array)
#2 {my_project}/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('bugsnag.logger', Array)
#3 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->re in {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag.logger does not exist' in {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('bugsnag.logger')
#1 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('bugsnag.logger', Array)
#2 {my_project}/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('bugsnag.logger', Array)
#3 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->re in {my_project}/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
```

What am I doing wrong?

**Comment by GrahamCampbell** [comment] 2016-08-17 16:18
Make sure you've put the bugsnag service provider above your app provider, and that you've run `php artisan config:cache`.

**Comment by rickytribbia** [comment] 2016-08-18 08:58
You're right, I put the service provider above app provider and it changes error:

```
 Uncaught exception 'InvalidArgumentException' with message 'Invalid API key'
```
(and I already have my `BUGSNAG_API_KEY` in `.env` file)

I solved it publishing config with:
```
php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider"
```

I see that the "service provider" order is suggested into [this doc page](https://docs.bugsnag.com/platforms/php/laravel/) but it isn't into bugsnag dashboard integration instructions. 

In all docs I see that isn't required to publish config file, but for me nothing works without it. 

Thanks for the support,
regards

**Comment by GrahamCampbell** [comment] 2016-08-18 09:10
> I solved it publishing config

Interesting. That shouldn't be necessary, but that's the 2nd report we've had. I'm going to look into this in more detail and get back to you.

**Comment by laravelian** [comment] 2016-09-15 15:05
This just happened for me -- probably shouldn't close the issue?

**Comment by Frozire** [comment] 2016-10-20 11:37
Just had the same problem, with the same solution.

Uncaught exception 'InvalidArgumentException' with message 'Invalid API key'

Solved by:

php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider"

**Comment by struyfv** [comment] 2016-11-02 12:45
I had the same issue and running php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider" did not help. I had to copy the config file manually.

**Comment by Numline1** [comment] 2017-05-17 12:21
I may be a little late, but perhaps this helps:

I accidentally loaded
```
Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,
```

after the AppServiceProvider (or in our case, BugsnagServiceProvider in App\Providers\, since we have a slightly different app structure).

Make sure to have them loaded in correct order.

**Comment by dbushy727** [comment] 2017-07-27 16:46
I had the same invalid api key issue and was also fixed by `php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider"`

**Comment by GrahamCampbell** [comment] 2017-07-27 20:05
> I had the same invalid api key issue and was also fixed by php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider"

That won't actually fix it, as such. It just has the side effect of fixing it, because it flushed the config cache. You can flush the config cache yourself by running the config cache artisan commands. You don't need to publish any resources to use bugsnag, but you can publish them if you really want to.

**Comment by cballou** [comment] 2017-09-22 10:58
The fix from my own personal experience is to ensure that you first run `php artisan config:cache` prior to updating the aliasing in your `AppServiceProvider`. This did the trick.

**Comment by asantibanez** [comment] 2017-10-19 20:18
I had the same issue today. I resolved it by placing the BugsnagServiceProvider before the AppServiceProvider in the providers array of my app. Hope it helps.

**Comment by russianryebread** [comment] 2018-03-20 22:00
My `BugsnagServiceProvider` has always been before the `AppServiceProvider`, but after running `composer update` today, and getting the latest version `v2.14.1` it broke with this error.  The fix was to manually copy the `bugsnag.php` config file from the vendor directory to the `config/` directory because even `artisan` gave the "Invalid API Key" error.

<img width="609" alt="screen shot 2018-03-20 at 4 57 18 pm" src="https://user-images.githubusercontent.com/747085/37685092-3125651e-2c60-11e8-978a-0c33c49ab9e2.png">

As soon as I copied the config file, it started working magically.

**Comment by Cawllec** [comment] 2018-03-21 09:00
Thanks for the information @russianryebread, I'll have a look into why this is occurring for you.

**Comment by GrahamCampbell** [comment] 2018-03-21 15:07
I wonder if the command is crashing, and trying to log to bugsnag which is causing this error, which is hiding the real error?

**Comment by gpopoteur** [comment] 2018-04-17 17:39
Fresh install, was driving me crazy trying to make it work, followed the comment from @russianryebread and it magically worked for me.

**Comment by Cawllec** [comment] 2018-04-23 10:47
I haven't been able to reproduce this error yet, on a fresh install with `v2.14.1` everything seems to work as expected, and commands such as `php artisan vendor:publish --provider="Bugsnag\BugsnagLaravel\BugsnagServiceProvider"` work correctly when copying the config across.

@gpopoteur any information such as laravel version or reproduction steps would be greatly appreciated.

**Comment by Numline1** [comment] 2018-04-23 12:32
@Cawllec I presume this happens when there's any other error and it triggers Bugsnag, which may not yet be configured. As @russianryebread mentioned above, it was an incorrect API key.

**Comment by Cawllec** [comment] 2018-04-23 14:41
Yes, I believe like @GrahamCampbell mentioned it's possible a different bug is occurring before Bugsnag initialises and the `Invalid API Key` issue replaces it in the console.

**Closed** 2018-09-20 09:34 UTC

**Comment by FoxRocks76** [comment] 2019-12-03 19:35
In case this helps anyone else...

My app was working as expected, but suddenly no Laravel Artisan commands would work without throwing this error. I can confirm that what @GrahamCampbell suggested was true in my case. I manually copied the bugsnag.php config file into the config directory, then the real error was now being displayed: 

> [Symfony\Component\Debug\Exception\FatalThrowableError] Parse error: syntax error, unexpected '{'

**Comment by mhimi1** [comment] 2020-04-12 11:14
The exception gets thrown because of a different error and this error is hidden by the Bugsnag error as @GrahamCampbell  mentioned. Best way to test whether this is the case in your case is to disable bugsnag temporarily and then run the command again and see whether you get the actual error. Then fix the error and enable bugsnag and you will find it fixed. Happened to me too.
