### ISSUE TITLE
Do not boot client if not in an environment that requires bugsnag

### ISSUE THREAD

**Issue by atrauzzi** [bugsnag/bugsnag-laravel#77] opened 2015-10-09 13:52 UTC
If I'm in an environment that won't be making use of bugsnag, the library shouldn't require that a key even be provided.  It should just fall through back to normal Laravel error reporting without attempting to instantiate the client.

**Comment by koorb** [comment] 2015-10-29 15:59
I agree, my continuous integration tests are failing because I'm not specifying an API key

**Comment by kattrali** [comment] 2016-01-05 17:06
Thanks for the report @atrauzzi. This makes a lot of sense, and should be fixed soon in #86. Closing this however as a duplicate of #65.

**Closed by kattrali** 2016-01-05 17:06 UTC

**Comment by atrauzzi** [comment] 2016-01-06 15:51
:+1: :D

**Comment by shineability** [comment] 2016-04-15 00:17
Hello!

 

New message, please read <http://autoinsurance365.xyz/talk.php?4i>

 

Maarten@troonbeeckx.net

**Comment by shineability** [comment] 2016-04-15 00:17
Hello!

 

New message, please read <http://brentallsupvacationspots.com/several.php?uem>

 

Maarten@troonbeeckx.net
