### ISSUE TITLE
Call to undefined method Bugsnag\BugsnagLaravel\LaravelLogger::popHandler()

### ISSUE THREAD

**Issue by bkuhl** [bugsnag/bugsnag-laravel#232] opened 2017-05-15 16:17 UTC
#207 I just added bugsnag to my project, see https://github.com/realpage/asset-publisher/blob/master/app/Providers/AppServiceProvider.php#L26 and https://github.com/realpage/asset-publisher/blob/master/bootstrap/app.php#L87.  When running `php artisan tinker` I see the following error:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Call to undefined method Bugsnag\BugsnagLaravel\LaravelLogger::popHandler()  
```

The project is Lumen 5.2

**Comment by GrahamCampbell** [comment] 2017-05-17 17:59
Thanks for the report. This is ultimately a duplicate of #231, since the fix will be the same. Thank you very much for reporting though. I'll close this up so we only have one issue. :)

**Closed by GrahamCampbell** 2017-05-17 17:59 UTC
