### ISSUE TITLE
Support Laravel 5.5 Package Discovery

### ISSUE THREAD

**Issue by finalgamer** [bugsnag/bugsnag-laravel#266] opened 2017-11-24 08:08 UTC
Add this to composer.json to make the package register the service provider and facade automatically.

composer.json
```
"extra": {
    "laravel": {
        "providers": [
            "Bugsnag\\BugsnagLaravel\\BugsnagServiceProvider"
        ],
        "aliases": {
            "Bugsnag": "Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag"
        }
    }
},
```

**Comment by Cawllec** [comment] 2017-11-24 09:34
Hi @finalgamer, thanks for the suggestion.  Unfortunately as we need our package to register before the `AppServiceProvider` we can't rely on package discovery.  Potentially this could be something we would support in the future.

**Comment by kattrali** [comment] 2017-11-28 02:23
Closing as duplicate of #236 and [more](https://github.com/bugsnag/bugsnag-laravel/search?q=auto-discovery&type=Issues&utf8=%E2%9C%93)

**Closed by kattrali** 2017-11-28 02:23 UTC
Labels: duplicate
